name: dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        type: choice
        options:
        - warning
        - info
        - debug
        default: warning
      environment:
        type: environment


jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
    - name: show-logs
      run: |
        echo "Log level: $LEVEL"
        echo "Tags: $TAGS"
        echo "Environment: $ENVIRONMENT"
      env:
        LEVEL: ${{ inputs.logLevel }}
        TAGS: ${{ inputs.tags }}
        ENVIRONMENT: ${{ inputs.environment }}
